import type { WaterGrid } from './waterMesh'

/** Baked grid = the mesh grid plus the WGS84 center it was localized around. */
export type BakedGrid = WaterGrid & { center: [number, number] }

const R_LAT = 110_540
const R_LNG = 111_320

/**
 * Parse GDAL `-of XYZ` text (one `lng lat elev` per line, row-major: top row =
 * max lat, left→right) into a WaterGrid localized around the grid center.
 * `nodataBelow` flags contaminated / nodata heights (default −1000) so any cell
 * touching one is dropped from `cellInMask`.
 */
export function xyzToGrid(lines: string[], cols: number, rows: number, nodataBelow = -1000): BakedGrid {
  const lng: number[] = new Array(cols * rows)
  const lat: number[] = new Array(cols * rows)
  const h: number[] = new Array(cols * rows)
  const valid: boolean[] = new Array(cols * rows)

  let i = 0
  for (const line of lines) {
    const t = line.trim()
    if (!t) continue
    const [x, y, z] = t.split(/\s+/).map(Number)
    lng[i] = x; lat[i] = y
    const ok = Number.isFinite(z) && z > nodataBelow
    valid[i] = ok
    h[i] = ok ? z : 0
    i++
  }

  const centerLng = (lng[cols - 1] + lng[0]) / 2               // top row spans full lng range
  const centerLat = (lat[0] + lat[(rows - 1) * cols]) / 2      // first col spans full lat range
  const kLng = R_LNG * Math.cos((centerLat * Math.PI) / 180)

  const xs = Array.from({ length: cols }, (_, c) => (lng[c] - centerLng) * kLng)
  const zs = Array.from({ length: rows }, (_, r) => -(lat[r * cols] - centerLat) * R_LAT)

  const cellInMask: boolean[] = []
  for (let r = 0; r < rows - 1; r++) {
    for (let c = 0; c < cols - 1; c++) {
      cellInMask.push(
        valid[r * cols + c] && valid[r * cols + c + 1] &&
        valid[(r + 1) * cols + c] && valid[(r + 1) * cols + c + 1],
      )
    }
  }

  return { cols, rows, xs, zs, h, center: [centerLng, centerLat], cellInMask }
}

// --- runner: generate marChiquitaGrid.ts from the DEM XYZ. Run with:
//     BAKE=1 npx tsx src/core/components/viewers/map/scenarios/mar-chiquita/bakeGrid.ts
// Emits a .ts module (not .json) so the core build ships it — see the header in
// marChiquitaGrid.ts for why a sibling .json import is dropped from dist.
export async function main() {
  const fs = await import('node:fs')
  const path = await import('node:path')
  const { fileURLToPath } = await import('node:url')
  const here = path.dirname(fileURLToPath(import.meta.url))
  const xyz = fs.readFileSync(path.join(here, 'data/work/dem_grid.xyz'), 'utf8')
  const grid = xyzToGrid(xyz.split('\n'), 180, 178)
  const module =
    `import type { BakedGrid } from './bakeGrid'\n\n` +
    `// Baked DEM grid for the Mar Chiquita water mesh. Generated by the runner in\n` +
    `// bakeGrid.ts. Stored as a .ts module, not .json, because the core build (tsup\n` +
    `// with bundle:false) emits only .ts/.tsx into dist — a sibling .json import is\n` +
    `// dropped and fails to resolve once the package is consumed.\n` +
    `const grid = ${JSON.stringify(grid)} as unknown as BakedGrid\n\nexport default grid\n`
  fs.writeFileSync(path.join(here, 'marChiquitaGrid.ts'), module)
  const valid = grid.cellInMask.filter(Boolean).length
  console.log(`grid: ${grid.cols}x${grid.rows}, cells in mask: ${valid}, center: ${grid.center}`)
}
if (process.env.BAKE) void main()
